name: MLflow Experiment Tracking

on:
  push:
    branches:
      - m2

jobs:
  mlflow_tracking:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Ensure S3 bucket exists
      run: |
        BUCKET_NAME="2023aa05704-mlops-assignment"
        REGION="ap-south-1"  # Change this to your desired region

        # Check if the bucket exists
        if ! aws s3api head-bucket --bucket $BUCKET_NAME --region $REGION 2>/dev/null; then
          echo "Bucket does not exist. Creating bucket $BUCKET_NAME..."
          aws s3api create-bucket --bucket $BUCKET_NAME --region $REGION --create-bucket-configuration LocationConstraint=$REGION
        else
          echo "Bucket $BUCKET_NAME exists."
        fi

    - name: Set MLflow Tracking URI
      run: echo "MLFLOW_TRACKING_URI=s3://mlops-assignment/mlflow" >> $GITHUB_ENV

    - name: Run MLflow Experiment
      run: |
        python src/mlflow_exp.py

